# Generated by Django 4.0.4 on 2022-11-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('Author', models.CharField(max_length=20)),
                ('Publish_date', models.DateField()),
            ],
        ),
    ]
